version: 5.1.0
variant: default
logo: /img/logo.png
head:
    favicon: /img/favicon.ico
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        首頁: /
        彙整: /archives
        分類: /categories
        標籤: /tags
    links:
        請我喝杯咖啡吧💖:
            icon: fas fa-coffee
            url: https://www.buymeacoffee.com/yurijournaltw
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: utterances
    repo: YuriTsaiTW/utterances-for-blog
    issue_term: pathname
    label: blog-comment
    theme: github-light
donates:
    -
        type: buymeacoffee
        url: https://www.buymeacoffee.com/yurijournaltw
share:
    type: sharethis
    install_url: https://platform-api.sharethis.com/js/sharethis.js#property=603f4a070e267500127ccaef&product=inline-share-buttons
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Yuri
        author_title: 主業是貓奴兼園丁🌱，副業是前端開發😎
        location: New Taipei City, Taiwan
        avatar:
        avatar_rounded: true
        gravatar:
    -
        position: left
        type: links
        links:
            ECMAScript關鍵30天-天瓏: https://www.tenlong.com.tw/products/9789864349197
            ECMAScript關鍵30天-博客來: https://www.books.com.tw/products/0010907980
            ECMAScript關鍵30天-金石堂: https://www.kingstone.com.tw/basic/2013120607606
            ECMAScript關鍵30天-momo: https://www.momoshop.com.tw/goods/GoodsDetail.jsp?i_code=9507720
            ECMAScript關鍵30天-讀墨: https://readmoo.com/book/210214657000101
    -
        position: left
        type: links
        links:
            Facebook: https://www.facebook.com/yurijournal.tw
            iT邦幫忙: https://ithelp.ithome.com.tw/users/20110962/profile
            GitHub: https://github.com/showwell0120
            CV: https://www.canva.com/design/DAEL_FC2F0I/f65yVy7utY01UjAw_big8Q/view?utm_content=DAEL_FC2F0I&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
    -
        position: right
        type: toc
        index: true
        collapsed: true
        depth: 2
    -
        position: right
        type: recent_posts
    -
        position: right
        type: categories
    -
        position: right
        type: tags
    -
        position: right
        type: archives
plugins:
    animejs: true
    back_to_top: true
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: G-RB9TX9FZV1
        localhost_ignored: true
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
